### ISSUE TITLE
Unable to get a sample running (translated to F#)

### ISSUE THREAD

**Issue by NatElkins** [m4rs-mt/ILGPU.Samples#7]
Hi,

Really interesting project!  I just thought I'd try to get the basic sample running in F#, but it failed with this error:

```
Performing operations on CPUAccelerator [WarpSize: 1, MaxNumThreadsPerGroup: 12, MemorySize: 9223372036854775807]
Unhandled exception. System.NotSupportedException: Class type 'Program+action@21' is not supported
   at ILGPU.IR.Types.IRTypeContext.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.IRContext.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.Construction.IRBuilder.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.Construction.IRBuilder.CreateType(Type type)
   at ILGPU.Frontend.CodeGenerator.SetupVariables()
   at ILGPU.Frontend.CodeGenerator..ctor(ILFrontend frontend, Builder methodBuilder, DisassembledMethod disassembledMethod, HashSet`1 detectedMethods)
   at ILGPU.Frontend.CodeGenerationPhase.GenerateCodeInternal(MethodBase method, Boolean isExternalRequest, HashSet`1 detectedMethods, Method& generatedMethod)
   at ILGPU.Frontend.ILFrontend.DoWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

My sample code is here: https://github.com/NatElkins/Scratchpad

To run, just clone the repo, do a `dotnet restore` and a `dotnet run`.

I tried to model it after this sample: https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/SimpleKernel/Program.cs

Thanks!

**Comment by MoFtZ** [comment]
hi @m4rs-mt, @NatElkins,

This looked interesting, so I decided to investigate.

The issue is that the F# compiler generates a class to wrap the static method used for the kernel.
```
    [CompilationMapping(SourceConstructFlags.Closure)]
    [Serializable]
    internal sealed class action@21
    {
        public action@21()
        {
        }

        internal void Invoke(Index arg00, ArrayView<int> arg10, int arg20)
        {
            Program.Test.MyKernel(arg00, arg10, arg20);
        }
    }
```

However, the auto-generated is not supported in ILGPU - it does not support classes yet.

I borrowed some code from the ILGPU codebase, and altered it to support F# functions. It uses reflection to extract the inner call to the static method.

See https://github.com/NatElkins/Scratchpad/pull/1

**Comment by m4rs-mt** [comment]
hi @NatElkins. As @MoFtZ said, the F# compiler usually generates many classes under the hood to "lower" the functional abstractions from F# to the .NET runtime. In this case, it is possible to extract the "kernel" function via another overload. However, this will not solve all problems that may occur when using F# programs in combination with ILGPU, as there is currently no support for reference types. In the future, we will add limited support for class types that support common lambda functions.
